### ISSUE TITLE
I want to add a project called "Snakes and Ladder", implemented in Java. 

### ISSUE THREAD

**Issue by ritikanagar09** [Lonewolf0502/DeveloperCode#147]
Though this project doesn't include the front end but gives a thorough understanding of how object-oriented programming is implemented in the real world. How different classes work together to form a game. 

![image](https://user-images.githubusercontent.com/87242161/197357803-426fdb66-6b58-4551-bcbb-b167bb02eae1.png)

**Comment by ritikanagar09** [comment]
Try to include it. You won't regret it.

**Comment by Lonewolf0502** [comment]
Sure

**Comment by ritikanagar09** [comment]
Sorry you closed it..before I submitted. Please try to open it again
