### ISSUE TITLE
Single Operation Part 1 : CODECHEF OCTOBER LONG CHALLENGE 2022

### ISSUE THREAD

**Issue by sahilsrivastava25** [Lonewolf0502/DeveloperCode#52]
@Lonewolf0502 Sir , Kindly assign this issue to me under Hacktober-Fest 2022 and labelled as hacktoberfest accepted.

**Comment by IamHetPatel** [comment]
Assign me the issue.

**Comment by Lonewolf0502** [comment]
sure

**Comment by sahilsrivastava25** [comment]
@Lonewolf0502 Sir , here's full description : - 
Problem Statement : - 
Chef has the binary representation SS of a number XX with him. He can modify the number by applying the operation exactly once.
Chef wants to maximize the value of XX after performing the operation. Help Chef in determining the value of YY which will maximize the value of XX after the operation.

Output - 
<img width="740" alt="Screenshot 2022-10-15 225004" src="https://user-images.githubusercontent.com/115632717/195999646-38b927fd-790a-4459-9f28-370f4c755de2.png">

**Comment by Lonewolf0502** [comment]
You can create pull request
