### ISSUE TITLE
Book Pages Allocation Problem :LeetCode Solution

### ISSUE THREAD

**Issue by aryananand27** [Lonewolf0502/DeveloperCode#74]
@Lonewolf0502 Kindly assign me this issue under Hacktoberfest 2022.

**Comment by Lonewolf0502** [comment]
sure
just give proper description and follow rules (fork + star +follow)

**Comment by aryananand27** [comment]
@Lonewolf0502 This problem states that a bunch of book pages has to be allocated to k number of students and through c++ code i have to find the minimum number of pages in maximum of allocation. Here i am adding my output also for convenience.
![2022-10-16](https://user-images.githubusercontent.com/108974142/196002842-e6bdc0c2-4c5a-46fb-8605-e998d65e416f.png)

**Comment by aryananand27** [comment]
Sir can i create pull request for this issue

**Comment by Lonewolf0502** [comment]
do the pull request
