### ISSUE TITLE
Dice Game challenge

### ISSUE THREAD

**Issue by Aditya-chaki** [Lonewolf0502/DeveloperCode#76]
@Lonewolf0502 Kindly assign me this under Hacktoberfest 2022.

**Comment by Lonewolf0502** [comment]
sure
just give proper description and follow rules (fork + star +follow)

**Comment by Aditya-chaki** [comment]
In this project , there are two dices . On pressing the refresh button , both dices rolls . Dice with higher number wins , winner name displays on the screen . If the both have same number , then "Draw" will be displayed .
