### ISSUE TITLE
add portfolio page

### ISSUE THREAD

**Issue by ShreeyashGarde** [Lonewolf0502/DeveloperCode#82]
hi messed up with the old repository pks assign me this issue again and add hacktoberfest tag , thank you.

**Comment by Lonewolf0502** [comment]
if you have messed up delete the forked repo and again fork it and upload your portfolio folder and then do pull request

**Comment by ShreeyashGarde** [comment]
yes will do , thanks.

**Comment by ShreeyashGarde** [comment]
done created anew repo and updated it as per told.

**Comment by Lonewolf0502** [comment]
will merge soon :)

**Comment by ShreeyashGarde** [comment]
Yes , thank you .
